version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon sECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME $ECR_REPOSITORY:latest
      - docker push $ECR_REPOSITORY:latest