version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Building Docker images...
      - docker-compose -f docker-compose-prod.yml build
  post_build:
    commands:
      - echo Pushing Docker images to DockerHub...
      - docker-compose -f docker-compose-prod.yml push