version: 0.2

phases:
  install:
    commands:
      - echo "Performing manual install of compose cli"
      - curl -L -o docker-linux-amd64.tar.gz https://github.com/docker/compose-cli/releases/download/v1.0.10/docker-linux-amd64.tar.gz
      - tar xzf docker-linux-amd64.tar.gz
      - chmod +x docker/docker
      - ls -ltr
      - docker/docker compose --help
      - which docker
      - ln -s $(which docker) /usr/local/bin/com.docker.cli
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - docker-compose version

  build:
    commands:
      - echo Building Docker images...
      - docker-compose -f docker-compose-prod.yml build

  post_build:
    commands:
      - echo Pushing Docker images to DockerHub...
      - docker-compose -f docker-compose-prod.yml push