version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - docker-compose version

  build:
    commands:
      - echo Building Docker images...
      - docker-compose -f docker-compose-prod.yml build

  post_build:
    commands:
      - echo Pushing Docker images to DockerHub...
      - docker-compose -f docker-compose-prod.yml push