version: '3.8'

networks:
  mptify_dev:
    driver: bridge

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    environment:
      - NODE_PORT=${NODE_PORT:-8000}
    volumes:
      - .:/usr/src/app
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - ${NODE_PORT:-8000}:8000
    networks:
      - mptify_dev